# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Rapidx-Devportal-CMSv4

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_0014deca2e82478b834dbbf8990c944b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8e846e3a4a394f1483318138c36ea884 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_0014deca2e82478b834dbbf8990c944b }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Rapidx-Devportal-CMSv4'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3c046d9843524ae3b5c71439896cbc43 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_0014deca2e82478b834dbbf8990c944b }}/appsvc/staticsite:${{ github.sha }}'